name: "OpenCode Code Review"
description: "AI-powered code review using OpenCode. Posts inline comments on PR files."
branding:
  icon: "eye"
  color: "purple"

inputs:
  model:
    description: "Model to use in provider/model format (e.g. anthropic/claude-sonnet-4-20250514)"
    required: true
  github_token:
    description: "GitHub token for posting review comments. Defaults to the built-in GITHUB_TOKEN."
    required: false
    default: ${{ github.token }}
  opencode_version:
    description: "OpenCode version to install (default: latest)"
    required: false
    default: "latest"
  review_prompt:
    description: "Custom review prompt to append to the default instructions. Use this to add project-specific review criteria."
    required: false
    default: ""
  max_diff_size:
    description: "Maximum diff size in bytes before truncation (default: 100000)"
    required: false
    default: "100000"
  post_summary:
    description: "Whether to post an overall summary comment on the PR (default: true)"
    required: false
    default: "true"
  extra_env:
    description: "Extra environment variables to pass to OpenCode as KEY=VALUE lines"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install OpenCode
      shell: bash
      run: |
        if command -v opencode &>/dev/null; then
          echo "OpenCode already installed: $(opencode --version)"
        else
          echo "Installing OpenCode..."
          curl -fsSL https://opencode.ai/install | bash
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        fi

    - name: Run review
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_REVIEW_PROMPT: ${{ inputs.review_prompt }}
        INPUT_MAX_DIFF_SIZE: ${{ inputs.max_diff_size }}
        INPUT_POST_SUMMARY: ${{ inputs.post_summary }}
        INPUT_EXTRA_ENV: ${{ inputs.extra_env }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
        # allow all tools without interactive prompts
        OPENCODE_PERMISSION: 'allow'
      run: |
        # Export any extra env vars the user passed
        if [ -n "$INPUT_EXTRA_ENV" ]; then
          while IFS= read -r line; do
            [ -n "$line" ] && export "$line"
          done <<< "$INPUT_EXTRA_ENV"
        fi

        bash "${{ github.action_path }}/scripts/review.sh"
